Heuristics for Fixed location archecture.  (#24)
* refactor dialects

* fixing tests

* updating kirin version

* Adding rewrites from circuit to moves

* updating doc strings and fixing bug in gemini

* updating tests

* simplifying StaticCircuit validation

* renaming file

* reformat imports

* adding doc strings

* Adding heuristic for merging regions

* Adding validation for lattice element

* generalizing archecture definition

* adding lane compatibility to arch

* adding missing features for last commit

* swapping heuristic to use lanes instead of location addresses

* updating strategy to include initial placement validation and reexporting base class

* adding update to global move count

* Renaming base class to be more clear

* Adding heristic for logical moves

* adding strategies for fixed location archecture

* Removing wrong import

* removing coverage from CI

* updating some names

* Refactor compute moves

* more refactors

* more refactors

* Adding some basic tests

* fixing bug

* fixing more bugs and adding tests

* Adding more tests

* Removing script

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,40 +34,40 @@ jobs:
       - name: Run tests
         # For example, using `pytest`
         run: uv run just coverage
-      - name: Upload Coverage to Codecov
-        uses: codecov/codecov-action@v5
-        with:
-          files: coverage.xml # optional
-          fail_ci_if_error: true # optional (default = false)
-          verbose: true # optional (default = false)
-          token: ${{ secrets.CODECOV_TOKEN }} # required
-      - name: Archive code coverage results
-        if: matrix.python-version == '3.12'
-        uses: actions/upload-artifact@v5
-        with:
-          name: code-coverage-report
-          path: coverage.xml
-          retention-days: 2
-  post:
-    runs-on: ubuntu-latest
-    needs: build
-    if: github.event.pull_request
-    steps:
-        - uses: actions/checkout@v5
-        - name: download coverage
-          uses: actions/download-artifact@v6
-          with:
-            name: code-coverage-report
-        - name: check coverage
-          run: |
-            if [ -f coverage.xml ]; then
-              echo "Coverage file exists"
-            else
-              echo "Coverage file does not exist"
-              exit 1
-            fi
-        - name: post coverage
-          uses: orgoro/coverage@v3.2
-          with:
-            coverageFile: coverage.xml
-            token: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Upload Coverage to Codecov
+  #       uses: codecov/codecov-action@v5
+  #       with:
+  #         files: coverage.xml # optional
+  #         fail_ci_if_error: true # optional (default = false)
+  #         verbose: true # optional (default = false)
+  #         token: ${{ secrets.CODECOV_TOKEN }} # required
+  #     - name: Archive code coverage results
+  #       if: matrix.python-version == '3.12'
+  #       uses: actions/upload-artifact@v5
+  #       with:
+  #         name: code-coverage-report
+  #         path: coverage.xml
+  #         retention-days: 2
+  # post:
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   if: github.event.pull_request
+  #   steps:
+  #       - uses: actions/checkout@v5
+  #       - name: download coverage
+  #         uses: actions/download-artifact@v6
+  #         with:
+  #           name: code-coverage-report
+  #       - name: check coverage
+  #         run: |
+  #           if [ -f coverage.xml ]; then
+  #             echo "Coverage file exists"
+  #           else
+  #             echo "Coverage file does not exist"
+  #             exit 1
+  #           fi
+  #       - name: post coverage
+  #         uses: orgoro/coverage@v3.2
+  #         with:
+  #           coverageFile: coverage.xml
+  #           token: ${{ secrets.GITHUB_TOKEN }}
